name: Test
on:
  workflow_dispatch:
    inputs:
      release_github:
        type: boolean
        description: Release on GitHub
        default: true
jobs:
  publish:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do something
        run: |
          echo "Hello"
          jq --help
          echo $?
      - name: Release GitHub
        uses: ncipollo/release-action@v1
        if: ${{ inputs.release_github }}
        with:
          name: "Release"
          token: ${{ secrets.GH_TOKEN }}
